-- 1. Users Table
CREATE TABLE users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(50) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    role VARCHAR(20) NOT NULL,
    cnic VARCHAR(20),
    is_active BOOLEAN DEFAULT TRUE
);

-- Default admin
INSERT INTO users (username, password, full_name, phone, role, is_active) 
VALUES ('admin', 'admin123', 'Super Admin', '0300-1234567', 'ADMIN', TRUE);


-- 2. Product Categories
CREATE TABLE product_categories (
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL
);


-- 3. Products
CREATE TABLE products (
    product_id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    barcode VARCHAR(50) PRIMARY KEY,
    product_name VARCHAR(200) NOT NULL,
    category_id INT REFERENCES product_categories(category_id) ON DELETE RESTRICT,
    price DECIMAL(10, 2) NOT NULL,
    cost_price DECIMAL(10, 2) NOT NULL,
    sales_quantity INT DEFAULT 0
);


-- 4. Inventory
CREATE TABLE inventory_items (
    inventory_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode VARCHAR(50) REFERENCES products(barcode) ON DELETE CASCADE,
    stock_quantity INT NOT NULL DEFAULT 0,
    min_stock INT NOT NULL DEFAULT 10,
    max_stock INT NOT NULL DEFAULT 100
);


-- 5. Bills
CREATE TABLE bills (
    bill_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES users(user_id) ON DELETE SET NULL,
    bill_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_amount DECIMAL(10, 2) NOT NULL,
    tax_amount DECIMAL(10, 2) DEFAULT 0,
    discount_amount DECIMAL(10, 2) DEFAULT 0,
    cash_provided DECIMAL(10, 2) NOT NULL,
    return_cash DECIMAL(10, 2) NOT NULL
);


-- 6. Bill Items
CREATE TABLE bill_items (
    bill_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id INT REFERENCES bills(bill_id) ON DELETE CASCADE,
    barcode VARCHAR(50) REFERENCES products(barcode) ON DELETE RESTRICT,
    quantity INT NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL
);


-- 7. Return Transactions
CREATE TABLE return_transactions (
    return_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_bill_id INT REFERENCES bills(bill_id) ON DELETE CASCADE,
    refund_amount DECIMAL(10, 2) NOT NULL,
    return_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reason VARCHAR(255)
);


-- 8. Return Items
CREATE TABLE return_items (
    return_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id INT REFERENCES return_transactions(return_id) ON DELETE CASCADE,
    bill_item_id INT REFERENCES bill_items(bill_item_id) ON DELETE CASCADE,
    return_quantity INT NOT NULL
);


-- 9. Sales Targets
CREATE TABLE sales_targets (
    target_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INT REFERENCES users(user_id) ON DELETE CASCADE,
    month INT NOT NULL,
    year INT NOT NULL,
    target_amount DECIMAL(10, 2) NOT NULL,
    achieved_amount DECIMAL(10, 2) DEFAULT 0
);