-- 1. Users Table (Stores Admins and Employees)
CREATE TABLE users (
    user_id INT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(50) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    role VARCHAR(20) NOT NULL,
    cnic VARCHAR(20), -- Only for employees
    is_active BOOLEAN DEFAULT TRUE
);

-- Insert a default admin account so you can log in immediately
INSERT INTO users (user_id, username, password, full_name, phone, role, is_active) 
VALUES (1, 'admin', 'admin123', 'Super Admin', '0300-1234567', 'ADMIN', TRUE);


-- 2. Product Categories Table
CREATE TABLE product_categories (
    category_id INT PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL
);


-- 3. Products Table
CREATE TABLE products (
    product_id INT UNIQUE NOT NULL,
    barcode VARCHAR(50) PRIMARY KEY,
    product_name VARCHAR(200) NOT NULL,
    category_id INT REFERENCES product_categories(category_id) ON DELETE RESTRICT,
    price DECIMAL(10, 2) NOT NULL,
    cost_price DECIMAL(10, 2) NOT NULL
);


-- 4. Inventory Items Table
CREATE TABLE inventory_items (
    inventory_id INT PRIMARY KEY,
    barcode VARCHAR(50) REFERENCES products(barcode) ON DELETE CASCADE,
    stock_quantity INT NOT NULL DEFAULT 0,
    min_stock INT NOT NULL DEFAULT 10,
    max_stock INT NOT NULL DEFAULT 100
);


-- 5. Bills Table
CREATE TABLE bills (
    bill_id INT PRIMARY KEY,
    user_id INT REFERENCES users(user_id) ON DELETE SET NULL,
    bill_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_amount DECIMAL(10, 2) NOT NULL,
    tax_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
    discount_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
    cash_provided DECIMAL(10, 2) NOT NULL,
    return_cash DECIMAL(10, 2) NOT NULL
);


-- 6. Bill Items Table
CREATE TABLE bill_items (
    bill_item_id INT PRIMARY KEY,
    bill_id INT REFERENCES bills(bill_id) ON DELETE CASCADE,
    barcode VARCHAR(50) REFERENCES products(barcode) ON DELETE RESTRICT,
    quantity INT NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL
);


-- 7. Return Transactions Table
CREATE TABLE return_transactions (
    return_id INT PRIMARY KEY,
    original_bill_id INT REFERENCES bills(bill_id) ON DELETE CASCADE,
    refund_amount DECIMAL(10, 2) NOT NULL,
    return_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reason VARCHAR(255)
);


-- 8. Return Items Table
CREATE TABLE return_items (
    return_item_id INT PRIMARY KEY,
    return_id INT REFERENCES return_transactions(return_id) ON DELETE CASCADE,
    bill_item_id INT REFERENCES bill_items(bill_item_id) ON DELETE CASCADE,
    return_quantity INT NOT NULL
);


-- 9. Sales Targets Table
CREATE TABLE sales_targets (
    target_id INT PRIMARY KEY,
    employee_id INT REFERENCES users(user_id) ON DELETE CASCADE,
    month INT NOT NULL,
    year INT NOT NULL,
    target_amount DECIMAL(10, 2) NOT NULL,
    achieved_amount DECIMAL(10, 2) NOT NULL DEFAULT 0
);

ALTER USER postgres WITH PASSWORD 'postgres';

CREATE SEQUENCE bill_items_id_seq;
ALTER TABLE bill_items ALTER COLUMN bill_item_id SET DEFAULT nextval('bill_items_id_seq');

CREATE SEQUENCE return_items_id_seq;
ALTER TABLE return_items ALTER COLUMN return_item_id SET DEFAULT nextval('return_items_id_seq');

ALTER TABLE products ADD COLUMN sales_quantity INT DEFAULT 0;


ALTER TABLE bills ALTER COLUMN bill_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE return_transactions ALTER COLUMN return_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE products ALTER COLUMN product_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE inventory_items ALTER COLUMN inventory_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE sales_targets ALTER COLUMN target_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE product_categories ALTER COLUMN category_id ADD GENERATED BY DEFAULT AS IDENTITY;


select * from products;
select * from inventory_items;


